[project]
name = "zsh-tips-agent"
version = "0.1.2"
description = "Agent that generates tips for underused CLI tools"
dependencies = [
  "smolagents",
  "litellm"
]

[tool.setuptools]
packages = ["agent"]
